export const MAX_AUDIO_FILE_SIZE_MB = 50;
export const MAX_AUDIO_FILE_SIZE_BYTES = MAX_AUDIO_FILE_SIZE_MB * 1024 * 1024;
export const MAX_AUDIO_FORM_FIELDS = 8;
export const MAX_AUDIO_FIELD_SIZE_BYTES = 16 * 1024;
